const single = `.foo { color: limegreen; }`;
const elmSingle = `-- Elm CSS Module, generated by postcss-elm-modules
module Styles exposing (styles)


styles =
    { foo = "file__foo---16mC4"
    }`;

function runElmModuleTests(resultString, expected) {
  return new Promise(resolve =>
    resolve(expect(resultString).toEqual(expected))
  );
}

module.exports = {
  cssFixtures: {
    single
  },
  elmSingle,
  runElmModuleTests
};
