const { buildElmModule } = require("../../src/index");

test("A properly formatted Elm module is generated.", () => {
  const expected = `-- Elm CSS Module, generated by postcss-elm-modules
module Styles exposing (styles)


styles =
    { foo = "foo"
    , bar = "bar"
    }`;
  expect(
    buildElmModule({ foo: "foo", bar: "bar" }, "Styles", "styles")
  ).toEqual(expected);
});
