const { opener } = require("../../src/index");

test("The opening string for the Elm module is properly formatted and named.", () => {
  const expected = `-- Elm CSS Module, generated by postcss-elm-modules
module Foo exposing (bar)


bar =
    { `;
  expect(opener("Foo", "bar")).toEqual(expected);
});
